cs_show_sbd_devices
fixed --config

diff --git a/ClusterTools2-SLE12/sbin/cs_show_sbd_devices b/ClusterTools2-SLE12/sbin/cs_show_sbd_devices
--- a/ClusterTools2-SLE12/sbin/cs_show_sbd_devices
+++ b/ClusterTools2-SLE12/sbin/cs_show_sbd_devices
@@ -35,20 +35,22 @@ case $1 in
 		exit
 	;;
 	-c|--config)
-        if !(test -r "$CFG"); then
-            echo "ERR: $CFG not found"
-            exit 1
-        fi
-		grep -v "^#" "$CFI" 
-        echo
+        	if !(test -r "$CFG"); then
+            		echo "ERR: $CFG not found"
+            	exit 1
+        	fi
+		echo
+		echo "$CFG"
+		grep -v "^#" "$CFG" | tr -s "\n"
+       		echo
 		grep -e dog -e wdt /etc/modules-load.d/*.conf
-        echo
-        # shellcheck disable=SC2162
-        awk -F"=" '$1=="SBD_DEVICE" {print $2}' "$CFG" |tr -d "\""|tr ";" "\n"|\
-        while read; do
-            sbd -d "$REPLY" dump 2>/dev/null; RC=$?
-        done
-
+        	echo
+        	# shellcheck disable=SC2162
+        	awk -F"=" '$1=="SBD_DEVICE" {print $2}' "$CFG" |tr -d "\""|tr ";" "\n"|\
+        	while read; do
+            		sbd -d "$REPLY" dump 2>/dev/null; RC=$?
+        	done
+		echo
 		exit
 	;;
 	-h|--help)
