major fixes

diff --git a/ClusterTools2/sbin/cs_stresscib b/ClusterTools2/sbin/cs_stresscib
--- a/ClusterTools2/sbin/cs_stresscib
+++ b/ClusterTools2/sbin/cs_stresscib
@@ -23,6 +23,7 @@ test -z "${F_CRON}" &&\
 test -z "${F_LOG}" &&\
 	F_LOG="/var/log/cs_stresscib.log"
 
+attr_store="reboot"			# reboot or forever
 
 # TODO better checks
 
@@ -32,17 +33,25 @@ function do_init() {
 	# check or create attributes in CIB?
 	LNK=2
 	test -L $F_CRON && LNK=0
-	test $LNK -eq 0 && echo "ERR: existing symlink: $F_CRON: RC=2" && exit 2
+	test $LNK -eq 0 && echo "ERR: do_init: existing symlink: $F_CRON: RC=2" >/dev/stderr && exit 2
 	test $LNK -eq 0 ||\
 		ln -s /usr/share/ClusterTools2/cs_stresscib.cron $F_CRON &&\
-		echo "INF: created symlink: $F_CRON: RC=0"
+		echo "INF: created symlink: $F_CRON: RC=0" >/dev/stderr
 		grep -v "^#" $F_CRON
 	touch $F_LOG
 	SVC=$(/sbin/chkconfig openais | tr -d " ")
 	if [ "$SVC" != openaison ]; then
-		echo "ERR: no chkconfig openais on: RC=$2"
+		echo "ERR: do_init: no chkconfig openais on: RC=$2" >/dev/stderr
 		exit 2
 	fi
+	time_stamp=$(/bin/date +%F_%H-%M-%S)
+	attr_value=${time_stamp}
+	for attr_node in ${L_NODE}; do
+		attr_name="val_stresscib_${attr_node}"
+		do_run_writehost 2>/dev/stderr ; RC=$?
+		echo "$time_stamp : do_init : $HOSTNAME ${attr_name} ${attr_value} : RC=$RC" >>$F_LOG
+		test $RC -eq 0 || echo "ERR: do_init: failed to initialise ${attr_name} : RC=$RC" 2>/dev/stderr
+	done
 }
 
 
@@ -51,16 +60,17 @@ function do_exit() {
 	test -L $F_CRON && LNK=0
 	test -e $F_CRON || LNK=0
 	test $LNK -eq 0 && rm -f $F_CRON &&\
-		echo "INF: removed symlink: $F_CRON: RC=0" && exit 0
-	test $LNK -eq 0 || echo "ERR: not a symlink: $F_CRON: RC=2" && exit 2
+		echo "INF: do_exit: removed symlink: $F_CRON: RC=0" >/dev/stderr && exit 0
+	test $LNK -eq 0 || echo "ERR: do_exit: not a symlink: $F_CRON: RC=2" >/dev/stderr && exit 2
+	# TODO remove attributes from CIB
 }
 
 
 function do_run() {
 
 	/etc/init.d/openais status >/dev/null 2>&1; RC=$?
-	if [ $RC -ne 0 ]; then
-		echo "ERR: openais not running: RC=$RC"
+	if [ "$RC" != "0" ]; then
+		echo "ERR: do_run: openais not running: RC=$RC"
 	# TODO double check if this works
 		exit $RC
 	fi
@@ -75,8 +85,6 @@ function do_run() {
 #		read	N_NODE		(planned ca.2 later)
 #
 
-	attr_store="reboot"			# reboot or forever
-
 	time_stamp=$(/bin/date +%F_%H-%M-%S)
 	# write host specific attributes, 6 x $N_NODE times
 	# TODO how many attributes: 6 x $N_NODE or $N_NODE ?
@@ -84,8 +92,8 @@ function do_run() {
 	attr_node=$HOSTNAME
 	for j in {1..6}; do
  		attr_name="val_stresscib_${attr_node}"
-		do_run_writehost
-		echo "$time_stamp: do_run_writehost: ${attr_node} $attr_name $attr_value: RC=$?"
+		do_run_writehost 2>/dev/null; RC=$?
+		echo "$time_stamp : do_run_writehost : ${attr_node} ${attr_name} ${attr_value} : RC=$RC"
 	done
 
 	time_stamp=$(/bin/date +%F_%H-%M-%S)
@@ -96,34 +104,36 @@ function do_run() {
 	NODE_2=$(echo $L_NODE | cut -d" " -f2)
 	if [ "$HOSTNAME" = "$NODE_1" -o "$HOSTNAME" = "$NODE_2" ]; then
 		attr_name="val_stresscib_cluster"
-		do_run_writecluster
-		echo "$time_stamp: do_run_writecluster: cluster $attr_name $attr_value: RC=$?"
+		do_run_writecluster; RC=$?
+		echo "$time_stamp : do_run_writecluster : cluster ${attr_name} ${attr_value} : RC=$RC"
 	fi
-	
+
 	time_stamp=$(/bin/date +%F_%H-%M-%S)
 	# read host specific attributes, $N_NODE x $N_NODE times
+	# TODO who writes all hosts attributes? do_run_writehosts writes only two
 	for attr_node in ${L_NODE}; do
 		attr_name="val_stresscib_${attr_node}"
-		attr_value=$(do_run_readhost)
-		echo "$time_stamp: do_run_readhost: ${attr_node} $attr_name $attr_value: RC=$?"
+		attr_value=$(do_run_readhost); RC=$?
+		echo "$time_stamp : do_run_readhost : ${attr_node} ${attr_name} ${attr_value} : RC=$RC"
 	done
 
 	time_stamp=$(/bin/date +%F_%H-%M-%S)
 	# read cluster specific attributes, $N_NODE times
 	attr_node=$HOSTNAME
 	attr_name="val_stresscib_cluster"
-	attr_value=$(do_run_readcluster | cut -d" " -f4 | cut -d"=" -f2)
-	echo "$time_stamp: do_run_readcluster: ${attr_node} $attr_name $attr_value: RC=$?"
+	attr_value=$(do_run_readcluster | cut -d" " -f4 | cut -d"=" -f2); RC=$?
+	echo "$time_stamp : do_run_readcluster : ${attr_node} ${attr_name} ${attr_value} : RC=$RC"
 }
 
 
 function do_run_writehost(){
+	# echo "/usr/sbin/crm_attribute -N ${attr_node} -v \"$attr_value\" -n \"$attr_name\" -l $attr_store -q"
 	/usr/sbin/crm_attribute -N ${attr_node} -v "$attr_value" -n "$attr_name" -l $attr_store -q
 }
 
 
 function do_run_readhost(){
-	/usr/sbin/crm_attribute -N ${attr_node} -G -n "$attr_name" -l $attr_store -q	
+	/usr/sbin/crm_attribute -N ${attr_node} -G -n "$attr_name" -l $attr_store -q
 }
 
 
@@ -140,7 +150,7 @@ function do_run_readcluster(){
 function do_run_cibadmin() {
 	time_stamp=$(/bin/date +%F_%H-%M-%S)
 	/usr/sbin/cibadmin -Q >/dev/null 2>&1; RC=$?
-	echo "$time_stamp: do_run_cibadmin: $HOSTNAME: RC=$RC"
+	echo "$time_stamp : do_run_cibadmin : $HOSTNAME : RC=$RC"
 }
 
 
